
SELECT ROUND(163.76, 1) FROM DUAL;
SELECT ROUND(163.76, -2) FROM DUAL;

SELECT FLOOR(22.3) FROM DUAL;

SELECT MOD(15, 7) FROM DUAL;

SELECT SYSDATE FROM DUAL;

-- 부속질의, 집계 함수
CREATE TABLE JOB(
    JOB_ID    VARCHAR2(10),
    SALARY    NUMBER(5)
);

INSERT INTO JOB VALUES ('manager', 1300);
INSERT INTO JOB VALUES ('manager', 1500);
INSERT INTO JOB VALUES ('manager', 1900);
INSERT INTO JOB VALUES ('helper', 1000);
INSERT INTO JOB VALUES ('helper', 1500);
INSERT INTO JOB VALUES ('helper', 2500);

SELECT * FROM JOB;

-- job 전체의 개수와 합계
SELECT COUNT(*) 개수, SUM(salary) 급여총계
FROM job;

-- job_id 별 개수와 급여 총계
SELECT job_id, COUNT(*) 개수, SUM(salary) 급여총계
FROM job 
GROUP BY job_id;

-- job_id 별 급여 총계와 소계
SELECT job_id, SUM(salary) salary
FROM job 
GROUP BY ROLLUP(job_id)
ORDER BY job_id;

-- job_id별 급여 최대값 구하기
SELECT job_id, MAX(salary) 급여최대
FROM job 
GROUP BY job_id;

-- job_id별 급여 최소값 구하기
SELECT job_id, MIN(salary) 급여최소
FROM job 
GROUP BY job_id;

-- 최대값, 최소값 더하기(합집합) - UNION
SELECT job_id, MAX(salary) 급여최대
FROM job 
GROUP BY job_id
UNION
SELECT job_id, MIN(salary) 급여최소
FROM job 
GROUP BY job_id;

SELECT * FROM job;

-- 테이블 이름 변경
ALTER TABLE JOB RENAME TO T_JOB;

CREATE TABLE A1(
    COL1 NUMBER(3)
);

CREATE TABLE B1(
    COL1 NUMBER(3)
);

CREATE TABLE C1(
    COL1 NUMBER(3)
);

INSERT INTO A1 VALUES(1);
INSERT INTO A1 VALUES(2);
INSERT INTO A1 VALUES(3);
INSERT INTO A1 VALUES(4);

INSERT INTO B1 VALUES(3);
INSERT INTO B1 VALUES(5);

INSERT INTO C1 VALUES(4);
INSERT INTO C1 VALUES(5);

-- UNION
SELECT * FROM A1
UNION 
SELECT * FROM B1;

-- MINUS
SELECT * FROM B1
MINUS 
SELECT * FROM C1;

SELECT * FROM A1
UNION 
SELECT * FROM B1
MINUS
SELECT * FROM C1;

-- LOLLUP, CUBE
CREATE TABLE DEPT(
    DEPT_NO VARCHAR2(3),
    JOB_NM  VARCHAR2(50),
    SALARY  NUMBER(5)
);

INSERT INTO DEPT VALUES ('100', '증권사', 3300);
INSERT INTO DEPT VALUES ('100', '관리자', 4300);
INSERT INTO DEPT VALUES ('200', '증권사', 5000);
INSERT INTO DEPT VALUES ('200', '데이터분석가', 4000);
INSERT INTO DEPT VALUES ('200', '관리자', 6000);

SELECT * FROM DEPT;

-- 부서 전체의 인원수와 급여 합계
SELECT COUNT(*) 인원수, SUM(salary) 급여합계
FROM dept;

-- 부서별, 직업 이름별 인원수, 급여합계
SELECT dept_no, job_nm, SUM(salary) 급여합계
FROM dept
GROUP BY dept_no, job_nm;

-- LOLLUP() : DEPT_NO별 소계 및 전체 총계
SELECT DEPT_NO, JOB_NM, SUM(SALARY) 
FROM DEPT
GROUP BY ROLLUP(DEPT_NO, JOB_NM)
ORDER BY DEPT_NO;

-- LOLLUP(): DEPT_NO별 총계
SELECT DEPT_NO, JOB_NM, SUM(SALARY) 
FROM DEPT
GROUP BY ROLLUP((DEPT_NO, JOB_NM));

-- CUBE() : DEPT_NO, JOB_NM별 소계 및 전체 총계
SELECT DEPT_NO, JOB_NM, SUM(SALARY) 
FROM DEPT
GROUP BY CUBE(DEPT_NO, JOB_NM)
ORDER BY DEPT_NO;

-- GROUPING SETS() : DEPT_NO, JOB_NM별 소계
SELECT DEPT_NO, JOB_NM, SUM(SALARY) 
FROM DEPT
GROUP BY GROUPING SETS(DEPT_NO, JOB_NM)
ORDER BY DEPT_NO;

-- GROUPING() 함수는 ROLLUP(), CUBE() 등과 함께 사용
-- GROUPING() 된 결과는 1로 출력됨
SELECT GROUPING(DEPT_NO), GROUPING(JOB_NM)
        DEPT_NO, JOB_NM, SUM(SALARY) 
FROM DEPT
GROUP BY ROLLUP(DEPT_NO, JOB_NM)
ORDER BY DEPT_NO;

-- NULL을 소계, 합계로 변경하기
SELECT 
        CASE GROUPING(DEPT_NO)
            WHEN 1 THEN '합계'
            ELSE DEPT_NO
       END DEPT_NO,
       CASE GROUPING(JOB_NM)
            WHEN 1 THEN '소계'
            ELSE JOB_NM
       END JOB_NM,
       SUM(SALARY) 
FROM DEPT
GROUP BY ROLLUP(DEPT_NO, JOB_NM)
ORDER BY DEPT_NO;



