
-- 사용자 계정 보기
SHOW USER;

-- 비밀번호 변경
ALTER USER SYSTEM IDENTIFIED BY pw1234;

ALTER USER C##JWEB IDENTIFIED BY pw4321;

ALTER USER C##SPRING IDENTIFIED BY pwspring;

ALTER USER C##SQLD IDENTIFIED BY pwsqld;

ALTER USER SYSTEM ACCOUNT UNLOCK;  -- 잠금 해제