-- 계층형 쿼리
CREATE TABLE FAMILY (
	FAMILY_ID	NUMBER,
	FAMILY_NAME	VARCHAR(15),
	PARENT_ID	NUMBER
);

INSERT INTO FAMILY VALUES (1,'할머니',NULL);
INSERT INTO FAMILY VALUES (2,'아빠',3);
INSERT INTO FAMILY VALUES (3,'할아버지',NULL);
INSERT INTO FAMILY VALUES (4,'엄마',1);
INSERT INTO FAMILY VALUES (5,'딸',4);
INSERT INTO FAMILY VALUES (6,'아들',2);

COMMIT;

SELECT * FROM FAMILY;

SELECT * FROM FAMILY
  -- PARENT_ID는 4에서 시작
  START WITH PARENT_ID = 4
  --이전 PARENT_ID와 FAMILY_ID 같은
 CONNECT BY FAMILY_ID = PRIOR PARENT_ID; 
/*
5  딸  4
4  엄마  1
1  할머니  null
*/

CREATE TABLE ORG_INFO (
	DEPT_CODE	VARCHAR(3),
	DEPT_NAME	VARCHAR(20),
	PARENT_DEPT	VARCHAR(3)
);

INSERT INTO ORG_INFO VALUES('100','이과계열',NULL);
INSERT INTO ORG_INFO VALUES('110','공학','100');
INSERT INTO ORG_INFO VALUES('111','컴퓨터','110');
INSERT INTO ORG_INFO VALUES('112','전자전기','110');
INSERT INTO ORG_INFO VALUES('113','건축','110');
INSERT INTO ORG_INFO VALUES('114','기계','110');
INSERT INTO ORG_INFO VALUES('120','자연','100');
INSERT INTO ORG_INFO VALUES('121','생물','120');
INSERT INTO ORG_INFO VALUES('122','화학','120');
INSERT INTO ORG_INFO VALUES('123','물리','120');
INSERT INTO ORG_INFO VALUES('124','수학','120');
INSERT INTO ORG_INFO VALUES('130','의약','100');
INSERT INTO ORG_INFO VALUES('131','의예','130');

COMMIT;

SELECT * FROM ORG_INFO;

-- LEVEL 사용
SELECT LEVEL, DEPT_NAME
  FROM ORG_INFO
  START WITH PARENT_DEPT IS NULL
  CONNECT BY PRIOR DEPT_CODE = PARENT_DEPT;  -- 순방향
  
SELECT LEVEL,
       SYS_CONNECT_BY_PATH(DEPT_NAME, '>') AS ORG,
       CONNECT_BY_ROOT DEPT_NAME AS ROOT,
       CONNECT_BY_ISLEAF  -- 맨 하위노드(1, 아니면 0)
  FROM ORG_INFO
  START WITH PARENT_DEPT IS NULL
  CONNECT BY PRIOR DEPT_CODE = PARENT_DEPT;

