-- CASE WHEN
CREATE TABLE CASEWHEN(
    COL1  NUMBER(1)
);

INSERT INTO CASEWHEN VALUES (NULL);
INSERT INTO CASEWHEN VALUES (0);
INSERT INTO CASEWHEN VALUES (NULL);
INSERT INTO CASEWHEN VALUES (0);
INSERT INTO CASEWHEN VALUES (NULL);

SELECT * FROM CASEWHEN;

SELECT 
    CASE 
      WHEN C.COL1 IS NULL THEN -1
      ELSE C.COL1
    END DATA1,
    DECODE(C.COL1, NULL, -1, C.COL1) DATA2
FROM CASEWHEN C;

-- CASE WHEN
CREATE TABLE Mytest(
    CLASS VARCHAR2(1),
    NAME  VARCHAR2(6)
);

INSERT INTO Mytest VALUES ('A', '조조');
INSERT INTO Mytest VALUES ('A', '조조');
INSERT INTO Mytest VALUES ('A', '조조');
INSERT INTO Mytest VALUES ('B', '유비');
INSERT INTO Mytest VALUES ('B', '관우');
INSERT INTO Mytest VALUES ('C', '여포');
INSERT INTO Mytest VALUES ('C', '여포');

-- 반별 인원수 계산
SELECT CLASS, COUNT(NAME) "RESULT"
FROM Mytest
GROUP BY CLASS;

-- 반별 인원수(중복 이름 제외) 계산
SELECT CLASS, COUNT(DISTINCT NAME) "RESULT"
FROM Mytest
GROUP BY CLASS;

-- 반별 인원수 - DECODE() 구문
SELECT 
    COUNT(DECODE(CLASS, 'A', 1)) AS A,
    COUNT(DECODE(CLASS, 'B', 1)) AS B,
    COUNT(DECODE(CLASS, 'C', 1)) AS C
FROM Mytest;

-- 반별 인원수 - CASE WHEN ~ END
SELECT 
    COUNT(CASE WHEN CLASS='A' THEN 1 
          END) A,
    COUNT(CASE WHEN CLASS='B' THEN 1 
          END) B,
    COUNT(CASE WHEN CLASS='C' THEN 1 
          END) C
FROM Mytest;



